name: Run python tests
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install and build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python leap_year_calculator.py
      - name: Run pytest
        run: |
          pytest -r w
